AllCops:
  TargetRubyVersion: 3.0.3
  NewCops: enable

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false
